title: Complexityland
author: "yeahBOYYYYY"
description: >
  This repository captures the human knowledge of the topic "Complexity Theory" in a shorthand way.


baseurl: "/"
url: "https://yeahboyyyyy.github.io/Complexityland"
github_username: yeahBOYYYYY
github_repository: Complexityland 


# SEO and Open Graph (for better link previews)
keywords: "complexity theory, computational complexity, P vs NP, mathematics, computer science"
lang: "en"
image: "Assets/math.png"
og:
  title: "Complexityland"
  description: "A repository capturing human knowledge on complexity theory."
  type: "website"
  url: "https://yeahboyyyyy.github.io/Complexityland/"
  image: "Assets/math.png"


# Build settings
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag

header_pages:
  - about.md

kramdown:
  math_engine: katex

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - LICENSE.md
  - README.md
  - Assets/
  - gitPush.bat
  - Gemfile
  - Gemfile.lock
